### ISSUE TITLE
where is the code for hybrid combination

### ISSUE THREAD

**Issue by gkrxqn** [GAMMA-UMD/GWA#2]

**Comment by Graphi07** [comment]
The crossover filtering is commonly found in DSP packages and you may use https://pyfar.readthedocs.io/en/latest/modules/pyfar.dsp.filter.html#pyfar.dsp.filter.crossover for now. Didn't include one because the combination step mainly involves interpreting file paths which can vary for everyone's local configuration and is non-technical. I may supply one in `tools` soon since you requested.

**Comment by Graphi07** [comment]
Please see updated `tools` folder.
